# Variabel

Diketahui beberapa list berikut:   
1. ipk = [3.05, 3.45, 3.33, 2.90, 3.10, 3.23, 3.80, 3.74, 3.67, 3.39, 3.41, 3.51, 3.21, 3.55, 3.34, 3.67, 3.77, 3.00, 3.25, 2.78]   
2. sks = [88, 89, 90, 100, 80, 78, 90, 90, 92, 97, 95, 80, 88, 102, 87, 84, 85, 89, 101, 80]
3. konsentrasi = konsentrasi = ["AK", "AK", "DS", "DS", "AK", "AK", "MK", "MK", "DS", "DS", "IN", "IN", "BS", "BS", "MK", "MK", "BS", "BS", "IN", "IN"]

In [ ]:
# definisi variabel
ipk = [3.05, 3.45, 3.33, 2.90, 3.10, 3.23, 3.80, 3.74, 3.67, 3.39, 3.41, 3.51, 3.21, 3.55, 3.34, 3.67, 3.77, 3.00, 3.25, 2.78]
sks = [88, 89, 90, 100, 80, 78, 90, 90, 92, 97, 95, 80, 88, 102, 87, 84, 85, 89, 101, 80]
konsentrasi = ["AK", "AK", "DS", "DS", "AK", "AK", "MK", "MK", "DS", "DS", "IN", "IN", "BS", "BS", "MK", "MK", "BS", "BS", "IN", "IN"]

In [ ]:
# panjang dari setiap variabel
len(ipk)

In [ ]:
# diperoleh nilai mata kuliah baru dengan bobot yang tersimpan dalam variabel bobot berikut
bobot = [3.0, 3.5, 4.0, 4.0, 4.0, 3.0, 3.5, 2.5, 2.8, 2.8, 3.0, 3.5, 3.8, 3.8, 3.8, 2.5, 4.0, 4.0, 3.8, 4.0]
print(bobot)

In [ ]:
len(bobot)

In [ ]:
# sks mata kuliah tersebut adalah 3. Hitung total bobot dengan mengalikan list bobot dengan 3. Simpan dalam variabel tot_bobot
tot_bobot = bobot*3


In [ ]:
# print out tot_bobot
print(tot_bobot)

In [ ]:
len(tot_bobot)

### apakah hasilnya sesuai yang diinginkan? 

# Menggunakan package numpy

Digunakan untuk manipulasi array secara mudah dan cepat. Daftar fungsi yang dapat digunakan dalam library numpy dapat diakses di [Numpy Array Manipulation](https://www.tutorialspoint.com/numpy/numpy_array_manipulation.htm). NumPy bekerja dengan array yang disebut ndarray. Dimensi array adalah tingkatan kedalaman dari suatu array. 



In [2]:
# import numpy sebagai np
import numpy as np

### 1. Membuat N-Dimensional Array

In [3]:
# Membuat 0-D Array

a = np.array(23)
print(a)

23


In [4]:
# Membuat 1-D array

b = np.array([1, 4, 6, 9])
print(b)

[1 4 6 9]


In [5]:
# Membuat 2-D array

c = np.array([[2, 3, 5], [7, 11, 13]])
print(c)

[[ 2  3  5]
 [ 7 11 13]]


In [7]:
# Membuat 3-D array

d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [21]:
# Membuat n-D array dengan numpy.array(array, ndmin = n)

e = np.array([[1, 2, 3], [4, 5, 6]], ndmin = 5)
print(e)

NameError: name 'np' is not defined

In [8]:
# Mengecek dimensi array dengan ndim

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

0
1
2
3
5


### 2. Indeks Array

Indeks array pada dasarnya digunakan untuk memanggil elemen di dalam array. 

In [ ]:
# Memanggil elemen pertama pada 1-D array
print(b[0])

In [ ]:
# Memanggil array pertama pada 2-D array
arr = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])
print(arr[0])

In [ ]:
# Memanggil elemen kedua pada array ketiga 2-D array

print(arr[2, 1])

### 3. Slicing Array

Slicing (memotong) maksudnya adalah mengambil elemen dari satu indeks ke indeks lain. Dengan kata lain, mengambil beberapa elemen. Slicing dapat dilakukan dengan menuliskan `[mulai : akhir]` atau `[mulai : akhir : langkah]`.   

- Jika `mulai` tidak dituliskan, maka dianggap 0
- Jika `akhir` tidak dituliskan, maka dianggap hingga panjang array
- Jika `langkah` tidak dituliskan, maka dianggap 1

In [9]:
arr = np.array([12, 15, 17, 20, 23, 34, 56, 78, 100, 56, 88])

# Mengambil elemen kedua hingga keenam (15, 17, 20, 23, 34)
arr[1:6]

array([15, 17, 20, 23, 34])

In [10]:
arr = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18], [19, 20, 21]], ndmin=2)

# Mengambil array pertama dan kedua (indeks 0, 1) beserta elemen pertama dan kedua (indeks 0, 1)
arr[0:2, 0:2]

array([[10, 11],
       [13, 14]])

### 4. Menggabungkan

Menggabungkan (join) array. Gunakan `np.concatenate`

In [ ]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([34, 56, 78, 90])

arr = np.concatenate((arr1, arr2))
print(arr)

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

# Jika axis = 0
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)

print("\n")

# Jika axis = 1
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

#### Menggabungkan array dengan stack

Kita dapat melakukan penggabungan array pada axis yang baru dengan fungsi stack.

In [ ]:
# Cobalah menggabungkan dua array berdimensi 1 berikut dengan stack
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis = 0)

print(arr)

In [ ]:
# Coba bandingkan apabila penggabungan dilakukan dengan menggunakan concatenate. Apa yang terjadi?
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2), axis = 0)

print(arr)

### 5. Random

Untuk merandim bilangan, kita import modul random dari numpy. 

In [ ]:
from numpy import random

In [ ]:
# Merandom bilangan bulat randint(low, high=None, size=None, dtype='l')


x = random.randint(10, 200, size = (4, 3))

print(x)

In [ ]:
x.ndim

In [ ]:
# Merandom bilangan diantara 0 dan 1 rand(10)
x = random.rand(10)

print(x)

In [ ]:
? random.rand()

# Latihan

## Isikan bagian None dengan suatu jawaban

In [39]:
import numpy as np

In [12]:
# Variabel tuple dari kasus terkonfirmasi positif dan sembuh
kasus = [[145, 100], [120, 111], [100, 80], [300, 242], [100, 233], [333, 368], [289, 228], [129, 125], [248, 137]]
print(type(kasus))

<class 'list'>


In [13]:
# ubah list kasus menjadi suatu array, simpan dalam np_kasus
np_kasus = np.array(kasus)
print(np_kasus)

[[145 100]
 [120 111]
 [100  80]
 [300 242]
 [100 233]
 [333 368]
 [289 228]
 [129 125]
 [248 137]]


In [14]:
# Berapakah ukuran dimensi array kasus?
print(kasus)

[[145, 100], [120, 111], [100, 80], [300, 242], [100, 233], [333, 368], [289, 228], [129, 125], [248, 137]]


In [15]:
# tampilkan tuple kasus ke-5
print(np_kasus[4])

[100 233]


In [16]:
# tampilkan semua kasus sembuh: 100, 111, 80 242 233 368 228 125 137
print(np_kasus[0:,1])

[100 111  80 242 233 368 228 125 137]


In [17]:
# tambahkan kasus terkonfirmasi 190, sembuh 233 pada np_kasus
np.append(np_kasus, [[190, 233]], axis=0)

array([[145, 100],
       [120, 111],
       [100,  80],
       [300, 242],
       [100, 233],
       [333, 368],
       [289, 228],
       [129, 125],
       [248, 137],
       [190, 233]])

In [3]:
def tabung(r, t):
    import math
    '''
    Fungsi untuk menghitung volume dan luas permukaan tabung
    '''
    l_lingkaran = math.pi*r*r
    volume = l_lingkaran*t
    l_permukaan = 2*math.pi*r*(r+t)
    return(volume, l_permukaan)

In [4]:
tabung (7, 10)

(1539.3804002589986, 747.6990515543707)

In [5]:
def manhattan(x1, y1, x2, y2):
    '''
    Fungsi menghitung jarak manhattan antara (x1, y1) dengan (x2, y2)
    '''
    abs1 = abs(x1 - x2)
    abs2 = abs(y1 - y2)
    jarak = abs1 + abs2
    return(jarak)

In [6]:
manhattan(-2, 18, 6, 10)

16

In [7]:
def jarak(x1, y1, x2, y2):
    '''
    Fungsi untuk menghitung jarak euclidean titik (x1, y1) dengan (x2, y2)
    '''
    import math
    kurang1 = (x1 - x2)**2
    kurang2 = (y1 - y2)**2
    jarak = math.sqrt(kurang1 + kurang2)
    return(jarak)

In [8]:
jarak(-10, 9, 20, -7)

34.0

In [35]:
indonia = [0.05, 0.06, 0.06, 0.07, 0.08]

In [36]:
np.array([0.05, 0.06, 0.06, 0.07, 0.08])

NameError: name 'np' is not defined

In [33]:
np.array(indonia)

NameError: name 'np' is not defined

In [40]:
arr = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18], [19, 20, 21]], ndmin=2)
arr[0:2, 1:3]

array([[11, 12],
       [14, 15]])

In [44]:
np.array([[1,2,3], [4,5,6]], ndmin=3)

array([[[1, 2, 3],
        [4, 5, 6]]])

In [45]:
indonia = [0.05, 0.06, 0.07, 0.08]

In [46]:
np.array (indonia)

array([0.05, 0.06, 0.07, 0.08])

In [47]:
np.array ([0.05, 0.06, 0.07, 0.08])


array([0.05, 0.06, 0.07, 0.08])

indonia = [0.05, 0.06, 0.07, 0.08]

In [ ]:
arr

In [54]:
arr = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18], [19, 20, 21]], ndmin=2)
arr[0:2, 1:4]

array([[11, 12],
       [14, 15]])